ir change proposal: NormArr
pallene-lang/pallene pull request #349
Opened 2021-01-21 22:57 UTC by leokaplan

This branch envision the optimization to renormalize_array calls.
A first step is to decouple the calls from SetArr and GetArr commands. 
Here I am proposing a new command, NormArr, that only performs renormalize_array calls.
Later we will be identifying the minimal amount of renormalize calls to be added to the emitted code.

2021-01-21 23:27 UTC, hugomg requested changes
Acho que também faltou botar os renormalizes do lado do `GetArr`?

Além disso, você poderia fazer o rebase dessa PR na versão mais recente do master, que contém a nova implementação do `ipairs`?

2021-01-21 23:27 UTC, hugomg commented on pallene/coder.lua
> +        {
Acho que não precisa desse `{}`.

2021-01-21 23:27 UTC, hugomg commented on pallene/coder.lua
> +gen_cmd["NormArr"] = function(self, cmd, _func)
Que tal chamar de `NormalizeArr`?

2021-01-21 23:27 UTC, hugomg commented on pallene/ir.lua
> +    NormArr    = {"loc", "src_typ",        "src_arr", "src_i"},
O que você acha de botar um comentário explicando as invariantes desses comandos?

```
    -- Arrays
    -- For performance reasons, GetArr and SetArr require that the index be in the array part of
    -- the Lua table. That is always the case for arrays returned by NewArr and by RenormalizeArr.
```

2021-01-21 23:27 UTC, hugomg commented on pallene/to_ir.lua
> +                -- that a new array is already normalized up to sizehint
Eu escreveria esse comentário como

```
-- We don't need to renormalize here because NewArr returns a normalized array
```

2021-01-21 23:30 UTC, hugomg commented
> Later we will be identifying the minimal amount of renormalize calls to be added to the emitted code.

Just to be clear, I'd prefer if that were on a separate optimization pass  instead of on the to_ir.

Sure, we can implement that optimization pass by deleting all the renormalize operations and adding them back in only where necessary. But either way, I'd be happier if we could put the complicated logic on a separate file.

2021-01-22 14:12 UTC, leokaplan commented
> > Later we will be identifying the minimal amount of renormalize calls to be added to the emitted code.
> 
> Just to be clear, I'd prefer if that were on a separate optimization pass instead of on the to_ir.
> 
> Sure, we can implement that optimization pass by deleting all the renormalize operations and adding them back in only where necessary. But either way, I'd be happier if we could put the complicated logic on a separate file.

I agree, that was already my plan. Sorry that it wasn't clear enough.

2021-01-22 14:59 UTC, hugomg commented
There is a test failing. Maybe it is because the code for `ipairs` also has a `GetArr` needs a NormalizeArr.

2022-04-22 16:33 UTC, closed without merging