Implement a -o option to select output path.
pallene-lang/pallene pull request #351
Opened 2021-02-18 15:10 UTC by srijan-paul

This Pull Request attempts to address Issue #321
Prior to this, Pallene was capable of emitting compiled files in the same directory as the source file.
Some small changes have been made to `pallenec` and `pallene/driver.lua (driver.compile)` to support a `-o` (`--output`) option that lets the user select an output directory. 

This works with all `--emit-x` flags as well.

Example:

```bash
# direct compilation
./pallenec my_dir/test.pln -o my_dir/__test_out.so

# pln -> c
./pallenec --emit-c  my_dir/test.pln -o my_dir/test_c_out.c

# c -> asm
./pallenec --emit-asm my_dir/test_c_out.c -o my_dir/__test_out.so

# pln -> lua
./pallenec --emit-lua my_dir/test.pln  -o my_dir/lua_dir/test_lua.lua
```

2021-02-18 17:12 UTC, hugomg requested changes
Hi, thanks for the PR!

I noticed that the PR message came with some examples of compiling with the `-o` flag. Could you also provide an example where you run the resulting code? The part that I'm particularly curious about is that in the generated C code, the name of the `luaopen` function includes the `modname`. I want to be sure that we're doing the right thing if the input base name is different from the output base name.

Finally, it would also be nice if we could add that example to the `pallenec_spec`. Something similar to the "Can compile pallene files" and/or "Can compile C files" test cases, but using the -o flag.

2021-02-18 17:12 UTC, hugomg commented on pallenec
> +p:option("-o --output", "Output file path.")
We can remove that period at the end

2021-02-18 17:15 UTC, srijan-paul commented on pallene/driver.lua
> +function driver.compile(argv0, input_ext, output_ext, input_file_name, opt_level, output_file_name)
I originally ordered it that way too, but my reason for this order was, the `output_file_path` argument is "optional" in the sense that it's assumed to be the same as the input file path when not provided / `nil`. And optional arguments are generally put at the end. 

That said, if we're only ever using `driver.compile` in `pallenec`, I guess I should reorder it like you said?

2021-02-18 17:24 UTC, hugomg commented
> I originally ordered it that way too, but my reason for this order 
> was, the output_file_path argument is "optional"
> 

The more important thing, in my opinion, is that the two file name 
arguments be next to each other. If we want to leave the output 
filename as an optional last argument, what we could do is move the 
`opt_level` before the file names. Either

    argv0, input_ext, output_ext, opt_level, input_file_name, 
output_file_name

or

    argv0, opt_level, input_ext, output_ext, input_file_name, 
output_file_name

2021-02-18 17:26 UTC, srijan-paul commented
>   argv0, opt_level, input_ext, output_ext, input_file_name,
output_file_name
I like this :+1:

2021-02-18 18:59 UTC, srijan-paul commented
> I want to be sure that we're doing the right thing if the input base name is different from the output base name.

I guess it's reasonable for the `modname` matches the output's name? Went with that assumption for now :p.
For example, if I have `a.pln ` as such: 

```lua
export function fn(a: float): float
    return a * 5.0
end
```
and compile it with `./pallenec a.pln -o b.so`, then the symbol generated is `luaopen_b(lua_State *L)`.
Testing it with a file `test.lua`:
```lua
local b = require "b"
print(b.fn(1.0))
```
![image](https://user-images.githubusercontent.com/50487716/108407098-4cb45d80-7249-11eb-84a9-fb98c888e21b.png)


> Finally, it would also be nice if we could add that example to the pallenec_spec

Added a test to `pallenec_spec`, it creates two new temporaries (`__test__flag__.so` and `__test__script__flag.lua`) to check if compiling to a different base name works. (`__test__.pln` -> `__test__flag__.so`).

2021-02-18 20:20 UTC, hugomg approved these changes
Great! Thanks again. Much appreciated.

2021-02-18 20:20 UTC, merged

2021-02-19 03:35 UTC, srijan-paul commented
Btw, Is it okay if I ask here when I run into any problems with embedding Pallene for the lack of a better place? (Problems with some relative file paths when including scripts and the bundled Lua interpreter, to be specific).

2021-02-19 03:51 UTC, hugomg commented
Good question.

This github repository is probably the best place to ask questions about Pallene in a place that most of the people involved will be able to see it. We tried setting up a mailing list a while back but I think everyone just ended up using github isntead of that  :)

Anyway, Github has a new feature for discussion forums where you can have discussions without needing to label them as "issues". We haven't used it yet but maybe we could give it a shot? I've just enabled it under https://github.com/pallene-lang/pallene/discussions

2021-02-19 05:24 UTC, srijan-paul commented
gotcha, thanks.